# Generated by Django 3.1.2 on 2021-01-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersys', '0003_auto_20201031_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=12),
        ),
    ]
