# Generated by Django 3.1.2 on 2021-01-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordersys', '0006_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordersys.product'),
        ),
    ]
