# Generated by Django 3.1.2 on 2021-01-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordersys', '0007_auto_20210123_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='amount_of_ingredient',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='productamount',
            old_name='amount_of_product',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='restock_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporder',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ordersys.employee'),
            preserve_default=False,
        ),
    ]
