# Generated by Django 3.1.6 on 2021-02-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersys', '0008_auto_20210124_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='restock_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
